### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#184]
- [x] app.json
- [x] app store assets (screenshots)
- [x] Give Beth access to apple developer account

Beta list:
- [x] Testflight stuff: https://developer.apple.com/testflight/
- [x] Android developer beta test stuff: https://support.google.com/googleplay/android-developer/answer/3131213?hl=en & https://support.google.com/googleplay/android-developer/answer/7159011

Two good resources: 
https://docs.expo.io/versions/v32.0.0/distribution/app-stores/
https://docs.expo.io/versions/v32.0.0/workflow/configuration/

The latter lists all the keys that can go into app.json. I added a few in this commit https://github.com/bpoore/pbm-react/pull/183/commits/9ce02623335bc68cf0a3c7d1b38d28823c4950ef

The app version will be 5.0.0. [The previous versions were both 4](http://blog.pinballmap.com/app). If we include the version in the expo key, it's unclear to me if we also need to include it in expo.android.

The biggest question I have right now is the `permissions` key for Android. `List of additional permissions the standalone app will request upon installation,` doesn't make sense to me, given that Android apps don't request permissions upon installation.

The current/live version of the android app requests:
````
   <uses-permission android:name="com.pbm.permission.MAPS_RECEIVE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="package.name.permission.MAPS_RECEIVE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        tools:node="remove" />
````

**Comment by bpoore** [comment]
I haven't compared the two sets of documents, but just to remember, we are currently on Expo 30.0, so we want to be checking these documents: 
https://docs.expo.io/versions/v30.0.0/distribution/app-stores/
https://docs.expo.io/versions/v30.0.0/workflow/configuration/

**Comment by RyanTG** [comment]
Good call. I was being lazy, just assuming the docs are the same.

**Comment by RyanTG** [comment]
I might have been hasty with that commit where I added some android permissions. I’m still uncertain if that’s necessary. Seems like it should be, but the app was working fine without it! But maybe it just works fine within Expo?

https://docs.expo.io/versions/v30.0.0/sdk/permissions/

We got feedback in the past when the iOS app didn’t specify that we were only using location while the app was in use. But it looks like we can’t control that request as well with expo. 

I don’t see the word Permission I our code anywhere. Just worried things will be wrong there when we eject.
