### ISSUE TITLE
Version 5.1.1 checklist

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#283]
- [x] [Android Dark Mode](https://github.com/bpoore/pbm-react/issues/281)
- [x] [Fix dark mode on location submission screen](https://github.com/bpoore/pbm-react/issues/280)
- [x] Upgrade SDK to 36.
- [x] ~~Resolve SDK upgrade warnings~~ I think it's fine to leave them for now.
- [ ] https://github.com/bpoore/pbm-react/issues/279
- [x] Android gesture navigation can work on Android. #278. And fix gestures on iOS.
- [x] Map flashes back to previous result. This is NOT magically fixed on SDK 36. https://github.com/bpoore/pbm-react/issues/285

Moved from this release to the next one: [Top 25 Machines](https://github.com/bpoore/pbm-react/issues/282)

**Comment by RyanTG** [comment]
about the warnings. https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Probably fine to leave them in now.

**Comment by RyanTG** [comment]
This turned into 5.1.1 (android) and 5.1.2 (both).
