### ISSUE TITLE
5.2 Outstanding Issues Checklist

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#309]
- [x] keyboard doesn't get dismissed when you scroll on the search screen (Android only); 
- [x] keyboard isn't visible when you first open that screen (you have to click again on the input box)
- [x] Location List crashes if location tracking is disabled. Probably because the "Distance" value is unknown.
- [x] Map still flashes back and forth sometimes.
~~Possible to use latest RNMaps and the isGesture function to determine map movement? https://github.com/bpoore/pbm-react/issues/324#issuecomment-826543193 (@bpoore)~~ Not ready for primetime yet.
- [x] Some flickering on the map. When you go back to the map from locationDetails, sometimes the map flickers once. Down/upgrade react navigation? Tried three versions of react-native-screens and it persisted on all of them. Solution: Downgrading react-native-screens even further. We should monitor that repo for updates.
- [ ] "I will come back to moving away from navigator.geolocation, but wanted to get this merged in the meantime."
instead just use expo-location methods through the apis they expose, eg:
```
import * as Location from 'expo-location';

// in your code
let location = await Location.getCurrentPositionAsync({});
```
- [ ] Can we speed up the Search autocomplete? (@bpoore)
- [x] First splash page dark mode looks weird
- [x] Fix search bar transparency stuff (@bpoore)
- [x] Edit Location: make inputs less rounded
- [x] Add horizontal padding to location name
- [x] Make the buttons on signup and login rounded. (@RyanTG)
- [x] Finish updating styles. Check Android. Check Light/Dark modes. Switch to staging server and test (@RyanTG)
- [x] Double check the location type icons to ensure they're the best! (@RyanTG)
- [x] Reduce margin on location Details on small devices.
- [x] I think the shadows on machineDetails are kinda wrong.
- [x] The loading spinner is not showing up in search on Android.
- [x] Location list is not full screen when there are not enough locations to full screen. Make it full screen no matter what.
- [x] Android onpress style for machine names looks ugly. Try replacing TouchableOpacity with Pressable. https://reactnative.dev/docs/pressable
- [x] Make machine comments selectable
- [x] Check horizontal margins on filter screen & profile edited locations list.
- [x] Reconsider “tool” icon on location details.
- [x] On location details, make back arrow more prominent.
- [x] Add pressable to Search this Area, and maybe make text color blue
- [x] Choose a different background color on splash.
- [x] Try slightly more prominent shadows (@RyanTG)
- [x] header background color on Location List is wrong. (@RyanTG)
- [x] On Map, adjust search bar position and try to remove the background color on the safeareaview (?) (@RyanTG)
- [x] Adjust stale notice colors in dark mode. (@RyanTG)
- [x] On Android, add # of machines to map callout (@RyanTG)
- [x] Check screens while logged out to see if there is any redundant text between header and body. (@RyanTG)
- [ ] My location Icon is square when pressed. (@RyanTG meh)
- [x] header bottom border is back after sdk 41 upgrade. Fixes https://github.com/react-navigation/react-navigation/issues/6899
- [x] The map is not changing to dark mode when toggling settings (@bpoore).
- [x] Put header back on machineDetails. And maybe a brown font color for location and machine names? (@RyanTG)
- [x] Add Stale text https://github.com/bpoore/pbm-react/issues/322 (@RyanTG)
- [x] On machineDetails, I removed the location name from the header and want to add it to the body (above "added to location"), but I couldn't figure it out (@RyanTG)
- [x] Fix Filter button functionality on map (@RyanTG)
- [x] Make sure Filter button is positioned OK on multiple devices. Search bar is too far left on Android. (@RyanTG)
- [x] Check on Header title width (@RyanTG)
- [x] Add Location Type icon to LocationDetails screen (@RyanTG)
- [x] Buttons looks fucked on Android - probably because of the shadows I'm trying to add. Either conditionally remove shadows based on OS, or... (@RyanTG)
- [x] Custom Button shadow seems to add a second shadow, rather than replacing the default shadow. How to fix? (@RyanTG)
- [x] Text is not selectable even when we set it to be selectable (@RyanTG)
- [x] Custom makers are really slow on Android. Test: 
- View (Master branch)
- Custom SVG (separate_android_ios_map_icons branch)
- Custom PNG (android-png-marker branch)
- Default Map Makers (default-android-marker branch)
- [x] Map refresh jump loop is still an issue. If we can't solve it, consider adding a "search this area" button whenever map is moved. https://github.com/bpoore/pbm-react/issues/319
- [x] Add `no_details=1` flag to closest_by_address and closest_by_lat_lon queries. Test.
- [x] Map results are not always refreshing on region change. https://github.com/bpoore/pbm-react/issues/312
- [x] On Android, LocationDetails, the machine condition text is not wrapping. I tried various flexbox tricks, and couldn't solve this! To replicate, visit Ground Kontrol, and see the comments going off the screen.
- [x] On Android, the spinning "loading" icon on screens is not showing up. This is resulting in a confusing blank white screen sometimes.
- [x] On LocationDetails, the marker dot alignment is off. It's too high. I'm not sure if the dot is in the wrong place or if the map just isn't centered.
- [x] https://github.com/bpoore/pbm-react/issues/306

**Comment by RyanTG** [comment]
@bpoore (as you know) I added an endpoint flag on closest_by_lat_lon that excludes some of the data we pull. Now e can test it.

PR: https://github.com/scottwainstock/pbm/pull/1273

Sample endpoint: http://localhost:3000/api/v1/locations/closest_by_lat_lon.json?lat=45.52819783271801;lon=-122.66291722170914;send_all_within_distance=10;no_details=1

Basically, just include `no_details=1`

I think I will also add this to `closest_by_address`. When we first lookup areas, this flag may speed up the initial loading of results. Couldn't hurt, right?

**Comment by RyanTG** [comment]
Another thought? I can't remember exactly why we're using out own component for "show my location". Was it only because we wanted a different icon? If so... I don't love our current icon. So maybe we should go back to using the default, since it's built into react-native-maps. `showsMyLocationButton=true`
