### ISSUE TITLE
List of Goals for being ready to beta test

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#95]
- [x] Profile Screen: https://github.com/bpoore/pbm-react/issues/38 (not super important to have done - but you said you're working on it next, so...)
- [x] Fix the autocomplete _list_ on Android. The list currently goes underneath the map. Current idea is to put it in a modal.
- [x] Saved Locations screen: https://github.com/bpoore/pbm-react/issues/40
- [x] Suggest a Location screen: https://github.com/bpoore/pbm-react/issues/41
- [x] Recent Activity screen: https://github.com/bpoore/pbm-react/issues/94
- [x] https://github.com/bpoore/pbm-react/issues/133
- [x] And better refine the search behavior, which we can chat about next week.
- [x] If a location that someone has Saved gets deleted from the db, then there are Saved Location errors https://github.com/scottwainstock/pbm/issues/1140
- [x] Decide how to construct the UserSubmissions "sentences" https://github.com/scottwainstock/pbm/issues/1144
- [x] Recent Activity "now" is probably wrong https://github.com/scottwainstock/pbm/issues/1143
~Get the PBM tiles working with the app! https://github.com/bpoore/pbm-react/issues/69~

**Comment by RyanTG** [comment]
We met all these goals!

But we should probably address a couple more things before beta testing:
- https://github.com/bpoore/pbm-react/issues/133
- And better refine the search behavior, which we can chat about next week.
